services:
  backend:
    image: ghcr.io/${IMAGE_NAME}-backend:main
    container_name: my-node-backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - /home/g2019171031/.env

  frontend:
    image: ghcr.io/${IMAGE_NAME}-frontend:main
    container_name: my-node-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
