services:
  backend-stable:
    image: ghcr.io/morgan24jm/colibri-pwa-backend:stable
    container_name: my-node-backend-stable
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - /home/g2019171031/.env
    environment:
      - INSTANCE=stable

  backend-canary:
    image: ghcr.io/morgan24jm/colibri-pwa-backend:main
    container_name: my-node-backend-canary
    restart: always
    ports:
      - "3002:3000"
    env_file:
      - /home/g2019171031/.env
    environment:
      - INSTANCE=canary

  frontend:
    image: ghcr.io/morgan24jm/colibri-pwa-frontend:main
    container_name: my-node-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend-stable

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.external-url=/prometheus/'
      - '--web.route-prefix=/prometheus/'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=http://35.223.54.114/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SECURITY_ADMIN_PASSWORD=admin123

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

volumes:
  prometheus_data:
  grafana_data:
